#!/usr/bin/env zsh

local var_name=$1 sec_name=vars k v var q
local -A vars
local -a tmp

vars=( "${(@kv)${(@PAkv)var_name}[(I)vars__*]}" )

for k v in ${(@kv)vars}; do
    var=${k##vars__}
    tmp=( "${(@)${(@kv)${(@PAkv)var_name}}//\%$var/$v}" )
    # Replace command subst.
    tmp=( "${(@)tmp//(#m)\$\([^\)]##\)/"$(eval q=\"$MATCH\"; print -rn -- $q)"}" )
    # Replace any "~dirs", including home ("~").
    tmp=( "${(@)tmp//(#m)(#s)\~[a-zA-Z0-9_]#/"$(eval print "$MATCH")"}" )
    # Replace any variables.
    tmp=( "${(@)tmp//(#b)(([^\\]|(#s))([\\][\\])#)(\$(\{|)[a-zA-Z0-9:,._\{\}\(\)\[\]-]##(\}|))/$match[1]"$(eval q=\"$match[4]\"; print -rn -- $q)"}" )
    tmp=( "${(Q)tmp[@]}" )
    : ${(@AP)var_name::="$tmp[@]"}
done

# vim:ft=zsh:sw=4:sts=4:ts=8:et
