# load zinit
source /src/zinit.zsh

# load zinit utilities
source /utils.zsh

# Custom setup
zinit::setup-keys

# Add ZPFX/bin to PATH
typeset -U path
path=("${ZPFX:-${HOME}/.zinit/polaris}/bin" $path)

# Install custom zsh version
if [[ -n "$ZINIT_ZSH_VERSION" ]]
then
  zinit::pack-zsh "$ZINIT_ZSH_VERSION"
fi

# Source init file
INIT_FILE="/init.zsh"
if [[ -r "$INIT_FILE" ]]
then
  source "$INIT_FILE"
fi

# vim: ft=zsh et ts=2 sw=2 :
