name: Bug Report
description: File a bug report
title: "[bug]: "
labels: ["bug", "triage"]
assignees:
  - vladdoster
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        ## Self Check

        - Look for similar errors in existing [GitHub Issues](https://github.com/zdharma-continuum/zinit/issues?q=is%3Aissue) (open or closed).
        - Try reaching out on the [Gitter server](https://gitter.im/zdharma-continuum/community/) for help.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the problem
      placeholder: |
        1. Enable plugin 'foo'
        2. Run 'foo bar' or try to complete command 'foo --widget'
        3. See error

  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Please copy and paste any relevant output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    attributes:
      label: Screenshots and recordings
      description: |
        If applicable, add screenshots or [asciinema](https://asciinema.org) session to explain your problem

  - type: input
    validations:
      required: true
    attributes:
      label: Operating System & Version
      description: |
        Output of 
        ```
        echo "OS: ${OSTYPE:-N/A} | Vendor: ${VENDOR:-N/A} | Machine: ${MACHTYPE:-N/A} | CPU: ${CPUTYPE:-N/A} | Processor: ${$(uname -p 2>/dev/null):-N/A} | Hardware: ${$(uname -m 2>/dev/null):-N/A}"
        ``` 

  - type: input
    validations:
      required: true
    attributes:
      label: Zsh version
      description: Output of `zsh --version`

  - type: input
    validations:
      required: true
    attributes:
      label: Terminal emulator
      description: Terminal name & output of `echo "${TERM}"`

  - type: dropdown
    attributes:
      label: If using WSL on Windows, which version of WSL
      description: Output `wsl -l -v`
      options:
        - 'WSL 1'
        - 'WSL 2'

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem. This can be themes, plugins, custom settings, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
