#!/usr/bin/env zsh
# -*- mode: sh;sh-indentation: 4;indent-tabs-mode: nil;sh-basic-offset: 4; -*-
# Copyright (c) 2020 Sebastian Gniazdowski

mg::cmd() {
    # Set the base and typically useful options.
    builtin emulate -L zsh -o extendedglob -o warncreateglobal \
                        -o typesetsilent -o noshortloops \
                        -o rcquotes

    local cmd=$2
    local -a args=($@[3,-1])
    local -A cmds=(
        build mg::cmd-build
        extract mg::cmd-extract
        load mg::cmd-load
        ls mg::cmd-ls
    )
    if [[ -z $cmds[$cmd] ]];then
        +zinit-message {pre}mg annex: {warn}unknown {cmd}mg\
            {warn}subcommand given \({cmd}$cmd{warn}\)
        return 1
    fi

    $cmds[$cmd] "$args[@]"
    return $?
}
