#!/usr/bin/env zsh
# -*- mode: sh;sh-indentation: 4;indent-tabs-mode: nil;sh-basic-offset: 4; -*-
# Copyright (c) 2020 Sebastian Gniazdowski

mg::before-load-handler() {
    # Set the base and typically useful options.
    builtin emulate -L zsh -o extendedglob -o warncreateglobal \
                        -o typesetsilent -o noshortloops \
                        -o rcquotes

    local type=$1 SID=$2 id_as=$3 args=$4 ices=$5 hook=$6 subtype=$7

    # Conditionally enable the output fr+om this annex
    integer IBSHOW_MESSAGES=$+ICE[debug]+$+ZINIT[DEBUG]

    # Exclude IDs with slashes and also packages
    [[ $SID != *.mg && $+ICE[mg] != 1 ]] && return 0
    [[ $SID == */* ]] && local BAD_ID=1 Q=1
    [[ $SID == *:* ]] && local BAD_ID2=1 Q=1
    (( $+ICE[pack] )) && local IS_PACK=1 Q=1
    if ((Q));then
        mg::msg "$BAD_ID" "$BAD_ID2" "$BAD_TELE" "$IS_PACK"
        return 1
    fi

    local -a match mbegin mend reply
    local MATCH REPLY
    integer MBEGIN MEND QRET

    local -A tpe_map
    tpe_map=( 0 plugin 1 snippet )

    # Strip the ID from some possible accidental /-s.
    SID=${${SID#@}%%(.mg|/##)##}

    # I've pressed C-J. Will now press C-J and C-H a few times
    # So the completion-method switching doesn't seem to work.
    mg::mount "$SID"
    QRET=$?
    if ((QRET));then
        if (( QRET == 8 ));then
            if [[ -z $ICE[mg] ]];then
                +zinit-message {e}no such miligram: \
                    {file}$SID.mg{error}, and no \
                    {pid}user/plugin {error}provided in \
                    {ice}mc\'\'{error} ice, cannot \(down\)load \
                    the miligram file{…}
                return QRET
            elif [[ $ICE[mg] != ([^/]##)/([^/]##) ]];then
                +zinit-message {e}no such miligram: \
                    {file}$SID.mg{error}, and incorrect {ice}mg\'\' \
                    {error}given, it should be in \
                    {pid}user/plugin {error}format, cannot  \
                    \(down\)load the miligram file{…}
                return QRET
            fi
        else
            return QRET
        fi
        mg::ghr::download-mg "$ICE[mg]" "$SID" ""||return $?
        mg::mount "$SID"||return $?
    fi

    ##
    ## Save in $Plugins hash
    ##

    Plugins[MG_PATH_$id_as]=$REPLY
    Plugins[MG_PID_$id_as]=$reply[1]

    ##
    ## Support messages
    ##

    if (( Zinit_Annex_Mg[enable-output] )) {
        # Clear the messages-flag, for cleanness
        Zinit_Annex_Mg[enable-output]=0

        # Enable the output from this annex
        # [Updated to disable via configuration]
        if (( $+ZINIT_ANNNEX_MG_HUMBLE ))
        then
            IBSHOW_MESSAGES=0
        else
            IBSHOW_MESSAGES=1
        fi
    }

    # Overwrite the outside parameters in order to introduce
    # the actual object's ID.
    ICE[id-as]=${id_as:-$___id} # cascade from ice to the phy-ID
    ___id=%$REPLY               # overwrite the physical-ID
    ___ehid=$ICE[id-as]         # handler ID – the id-as'' ice
    ___etid=%$REPLY             # folder path (via preceding %)
    ICE[teleid]=%$REPLY         # folder path (via preceding %)

    # Debug message.
    if ((IBSHOW_MESSAGES));then
        +zinit-message {pre}mg annex: {msg}Matched \
            the miligram to its dir: \
            {meta}$SID {ehi}→ {b}{file}${ICE[teleid]#%}
    fi

    return 0
}

# vim:ft=zsh:tw=80:sw=4:sts=4:et
