#!/usr/bin/env zsh

# Set TERM or various ices might be ignored
# https://github.com/zdharma-continuum/zinit/issues/97
export TERM=${TERM:-xterm-256color}
export SHELL=${${commands[zsh]}:-SHELL}

typeset -Ag ZINIT

export ZINIT[HOME_DIR]=${ZINIT_HOME_DIR:-/data}
export ZINIT[BIN_DIR]=/src
