# Fix permissions on /data (run only once, at startup)
if [[ "$$" == 1 ]]
then
  if [[ -z "$QUIET" ]]
  then
    echo "Setting owner of /data to ${PUID}:${PGID}" >&2
  fi
  sudo chown /data
  sudo chown -R "${PUID}:${PGID}" /data
fi

# load zinit
source /src/zinit.zsh

# load zinit setup utility functions
source /src/docker/utils.zsh

# Add ZPFX/bin to PATH
typeset -U path
path=("${ZPFX:-${HOME}/.local/share/zinit/polaris}/bin" $path)

# Install custom zsh version
if [[ -n "$ZINIT_ZSH_VERSION" ]]
then
  zinit::pack-zsh "$ZINIT_ZSH_VERSION"
fi

# Source init file
INIT_FILE="/init.zsh"
if [[ -r "$INIT_FILE" ]]
then
  source "$INIT_FILE"
fi

# Setup keys
zinit::setup-keys

# vim: ft=zsh et ts=2 sw=2 :
