#!/usr/bin/env zsh

_annex_test_function() {
  # run zinit load zdharma-continuum/${1}
  run zinit id-as ver'style/rename-funcs' for load vladdoster/${1}
  assert ${state} equals 0
  zinit cd ${1}
  assert ${PWD}/${${1}//zinit-annex/z-a}.plugin.zsh is_file
  assert ${PWD}/${${1}//zinit-annex/z-a}.plugin.zsh is_readable
}
