name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch dependencies
        run: |
          npm install --no-package-lock \
            @semantic-release/changelog @semantic-release-plus/docker @semantic-release/exec @semantic-release/git \
            conventional-changelog-eslint @google/semantic-release-replace-plugin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate release
        run: npx semantic-release --ci --
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: 'mvdoster@gmail.com'
          GIT_AUTHOR_NAME: 'Vladislav Doster'
          GIT_COMMITTER_EMAIL: 'mvdoster@gmail.com'
          GIT_COMMITTER_NAME: 'Vladislav Doster'

  bump-homebrew-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Bump Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          formula: zinit
          org: zdharma-continuum
          # A Personal Access Token (PAT) is instead of the default
          # GITHUB_TOKEN because brew bump-formula-pr creates a fork of the
          # formula's tap repository (if needed) and then creates a pull
          # request.
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
