name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch dependencies
        run: |
          npm install --no-package-lock \
            @semantic-release/changelog @semantic-release-plus/docker @semantic-release/exec @semantic-release/git \
            conventional-changelog-eslint @google/semantic-release-replace-plugin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build Docker image
      #   run: docker buildx --load build --tag vladdoster/dotfiles:latest .

      - name: Generate release
        run: npx semantic-release --ci --
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: 'mvdoster@gmail.com'
          GIT_AUTHOR_NAME: 'Vladislav Doster'
          GIT_COMMITTER_EMAIL: 'mvdoster@gmail.com'
          GIT_COMMITTER_NAME: 'Vladislav Doster'
