name: tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 0
  HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
  TERM: xterm-256color
  # TERM: dumb

on:
  pull_request:
    branches:
      - main
    paths:
      - "tests/**"
      - "share/**"
      - "zinit*.zsh"
      - ".github/workflows/tests.yaml"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zunit-tests:
    name: "${{ matrix.zunit_test }} | ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        zunit_test:
          - annexes
          - commands
          - compile
          - config-zstyle
          - gh-r
          - hook-handler
          - ice-validation
          - ices
          - plugins
          - snippets
        os: [macos, ubuntu]
        include:
          - zunit_test: gh-r
            zunit_flag: --slice
          - zunit_test: plugins
            zunit_flag: --slice

    steps:
      - name: "checkout ${{ github.repository }}"
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: "install homebrew"
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@a657b8b0cd35d0f65cce41fce9b24cf054b49869

      - name: "install ${{ runner.os }} dependencies"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update --yes
          sudo apt-get install --no-install-recommends --yes \
            autoconf automake autotools-dev \
            build-essential byacc \
            file \
            gcc gettext glibc-source grep \
            libc6 libc6-dev libevent-dev libncurses5-dev libncursesw5-dev libtool libuvc0 lua5.1 \
            m4 \
            ninja-build \
            pkg-config \
            xz-utils \
            zsh \
            zstd

      - name: "install dependencies via brew"
        id: install-deps
        run: |
          brew install --quiet --force --overwrite autoconf automake binutils byacc coreutils curl gettext gnu-sed jemalloc libevent libtool libuv lua lua@5.4 make ninja parallel pkg-config texinfo unzip xz zsh zstd
          brew unlink ncurses && brew link --force ncurses

      - name: "checkout zdharma-continuum/zunit"
        uses: actions/checkout@v7
        with:
          repository: "zdharma-continuum/zunit"
          path: zunit
          ref: "feat/run-tests-in-parallel-support"

      - name: "install zunit"
        id: install-zunit
        shell: zsh {0}
        working-directory: zunit
        run: |
          mkdir -p "${HOME}/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ./configure --prefix=${HOME}/.local
          make all install

      - name: "run ${{ matrix.zunit_test }} tests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: zunit run ${{ matrix.zunit_flag }} tests/${{ matrix.zunit_test }}.zunit
